import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import { library } from "@fortawesome/fontawesome-svg-core";

import {
  faHome,
  faPhone,
  faEnvelope,
  faCircleUser,
  faArrowTurnDown,
  faArrowRightToBracket,
  faSearch,
  faPen,
  faCheck,
  faClose,
  faPencil,
  faCamera,
  faFileImage,
  faEllipsis,
  faArrowsUpDown,
  faDownload,
  faFileInvoice,
  faPenToSquare,
  faPlus,
  faX,
  faPeopleGroup,
  faCaretLeft,
  faPaperclip,
  faChevronUp,
  faChevronDown,
  faChevronRight,
  faEye,
  faEyeSlash,
  faNetworkWired,
  faUpload,
  faHandPointRight,
  faStar,
  faTrash,
  faCalendarDays,
  faMinus,
  faAddressBook,
  faBriefcase,
  faCommentDots,
  faUserGear,
  faHandshake,
  faFile,
  faBars,
  faGrip,
  faArrowRight,
  faInfo,
  faCircleInfo,
  faTrashCan,
  faCopy,
  faPaste,
  faPersonCircleQuestion,
  faAngleLeft,
  faArrowUpWideShort,
  faAnglesLeft,
  faAngleRight,
  faAnglesRight,
  faBell,
  faStopwatch,
  faFolderTree,
  faFolder as faFolderSolid,
  faRotate,
  faEllipsisVertical,
  faCircleCheck,
  faCircleXmark,
  faFileExcel,
  faFilePdf,
  faFileWord,
  faFilePowerpoint,
  faFileZipper,
  faFileCode,
  faFolder,
  faFileVideo,
  faFileLines,
  faUserGroup,
  faArrowLeft,
  faArrowUpShortWide,
  faSort,
  faArrowDownShortWide,
  faFolderPlus,
  faCircleExclamation,
} from "@fortawesome/free-solid-svg-icons";

import {
  faCircleUser as faCircleUserRegular,
  faCircleCheck as faCircleCheckRegular,
  faCircleXmark as faCircleXmarkRegular,
  faFile as faFileRegular,
  faFileExcel as faFileExcelRegular,
  faFilePdf as faFilePdfRegular,
  faFileWord as faFileWordRegular,
  faFilePowerpoint as faFilePowerpointRegular,
  faFileZipper as faFileZipperRegular,
  faFileCode as faFileCodeRegular,
  faFolder as faFolderRegular,
  faFileVideo as faFileVideoRegular,
  faFileLines as faFileLinesRegular,
  faFileImage as faFileImageRegular,
} from "@fortawesome/free-regular-svg-icons";

library.add(
  faHome,
  faArrowsUpDown,
  faPhone,
  faEllipsis,
  faArrowUpShortWide,
  faPenToSquare,
  faCircleInfo,
  faCircleUser,
  faCircleUserRegular,
  faTrashCan,
  faArrowTurnDown,
  faArrowRightToBracket,
  faSearch,
  faPencil,
  faPen,
  faCheck,
  faCircleCheck,
  faCircleCheckRegular,
  faCircleXmark,
  faCircleXmarkRegular,
  faEnvelope,
  faClose,
  faCamera,
  faFileImage,
  faDownload,
  faFileInvoice,
  faArrowUpWideShort,
  faSort,
  faArrowDownShortWide,
  faPlus,
  faCalendarDays,
  faArrowLeft,
  faX,
  faPeopleGroup,
  faCaretLeft,
  faPaperclip,
  faChevronUp,
  faChevronDown,
  faChevronRight,
  faEye,
  faEyeSlash,
  faBriefcase,
  faNetworkWired,
  faUpload,
  faInfo,
  faHandPointRight,
  faStar,
  faTrash,
  faMinus,
  faAddressBook,
  faCommentDots,
  faUserGear,
  faFile,
  faBars,
  faGrip,
  faArrowRight,
  faCopy,
  faPaste,
  faPersonCircleQuestion,
  faAngleLeft,
  faAnglesLeft,
  faAngleRight,
  faAnglesRight,
  faBell,
  faFolderTree,
  faFileExcel,
  faFilePdf,
  faFileWord,
  faFilePowerpoint,
  faFileZipper,
  faFileCode,
  faFolder,
  faFileVideo,
  faFileLines,
  faFolderSolid,
  faFileRegular,
  faFileZipperRegular,
  faFileCodeRegular,
  faFolderRegular,
  faFileVideoRegular,
  faFileLinesRegular,
  faFileExcelRegular,
  faFilePdfRegular,
  faFileWordRegular,
  faFilePowerpointRegular,
  faRotate,
  faEllipsisVertical,
  faFileImageRegular,
  faStopwatch,
  faUserGroup,
  faHandshake,
  faFolderPlus,
  faCircleExclamation
);

export { FontAwesomeIcon };
